server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:\\C:\workspace\msa-study\git-local-repo
          uri: https://github.com/fluffymn/spring-cloud-config.git
#          username: [your password]
#          password: [your username]